/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPCGEN_H_RPCGEN
#define _RPCGEN_H_RPCGEN

#include <rpc/rpc.h>
#include "DIO_Interface.h"

#ifdef __cplusplus
extern "C" {
#endif


struct result {
	Error_t Func_Status;
};
typedef struct result result;

struct param {
	DIO_Channels_t DIO_Channel;
	BitStatus_t pinStatus;
};
typedef struct param param;

#define GOLDEN_BOX_PROG 0x20650609
#define GOLDEN_BOX_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define DIO_SetPinValue 1
extern  Error_t * dio_setpinvalue_1(param *, CLIENT *);
extern  Error_t * dio_setpinvalue_1_svc(param *, struct svc_req *);
extern int golden_box_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define DIO_SetPinValue 1
extern  Error_t * dio_setpinvalue_1();
extern  Error_t * dio_setpinvalue_1_svc();
extern int golden_box_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_result (XDR *, result*);
extern  bool_t xdr_param (XDR *, param*);
extern bool_t xdr_Error_t (XDR *__xdrs, Error_t *__error);
extern bool_t xdr_DIO_Channels_t (XDR *__xdrs, DIO_Channels_t *__dio_channel);
extern bool_t xdr_BitStatus_t (XDR *__xdrs, BitStatus_t *__bit_status);

#else /* K&R C */
extern bool_t xdr_result ();
extern bool_t xdr_param ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPCGEN_H_RPCGEN */
