/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _DIO_H_RPCGEN
#define _DIO_H_RPCGEN


extern  uint8_t DO_CH_SET(uint8_t digital_channel);

extern  uint8_t DO_CH_RESET(uint8_t digital_channel);

extern  uint8_t DIO_CH_GET(uint8_t digital_channel);


#endif /* !_DIO_H_RPCGEN */
